// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, DomCharacterData, DomNode};
use glib::{prelude::*, translate::*};

glib::wrapper! {
///
///
/// # Implements
///
/// [`DomCharacterDataExt`][trait@crate::prelude::DomCharacterDataExt], [`DomNodeExt`][trait@crate::prelude::DomNodeExt], [`trait@glib::ObjectExt`]
	#[doc(alias = "ArvDomText")]
	pub struct DomText(Object<ffi::ArvDomText, ffi::ArvDomTextClass>) @extends DomCharacterData, DomNode;

	match fn {
		type_ => || ffi::arv_dom_text_get_type(),
	}
}

impl DomText {
	pub const NONE: Option<&'static DomText> = None;

	#[doc(alias = "arv_dom_text_new")]
	pub fn new(data: &str) -> DomText {
		assert_initialized_main_thread!();
		unsafe {
			DomNode::from_glib_full(ffi::arv_dom_text_new(data.to_glib_none().0)).unsafe_cast()
		}
	}
}

unsafe impl Send for DomText {}
