// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, Interface};
use glib::translate::*;

glib::wrapper! {
///
///
/// # Implements
///
/// [`InterfaceExt`][trait@crate::prelude::InterfaceExt], [`trait@glib::ObjectExt`]
	#[doc(alias = "ArvFakeInterface")]
	pub struct FakeInterface(Object<ffi::ArvFakeInterface, ffi::ArvFakeInterfaceClass>) @extends Interface;

	match fn {
		type_ => || ffi::arv_fake_interface_get_type(),
	}
}

impl FakeInterface {
	/// Gets the unique instance of the fake interface.
	///
	/// # Returns
	///
	/// a [`Interface`][crate::Interface] singleton.
	#[doc(alias = "arv_fake_interface_get_instance")]
	#[doc(alias = "get_instance")]
	pub fn instance() -> Option<Interface> {
		assert_initialized_main_thread!();
		unsafe { from_glib_none(ffi::arv_fake_interface_get_instance()) }
	}
}

unsafe impl Send for FakeInterface {}
