// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::DomElement;
use crate::DomNode;
use crate::GcFeatureNode;
use crate::GcFloat;
use crate::GcNode;
use crate::GcRegister;
use crate::GcRegisterNode;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
	#[doc(alias = "ArvGcFloatRegNode")]
	pub struct GcFloatRegNode(Object<ffi::ArvGcFloatRegNode, ffi::ArvGcFloatRegNodeClass>) @extends GcRegisterNode, GcFeatureNode, GcNode, DomElement, DomNode, @implements GcRegister, GcFloat;

	match fn {
		type_ => || ffi::arv_gc_float_reg_node_get_type(),
	}
}

impl GcFloatRegNode {
	///
	/// # Returns
	///
	/// a new FloatReg node
	#[doc(alias = "arv_gc_float_reg_node_new")]
	pub fn new() -> GcFloatRegNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_float_reg_node_new()).unsafe_cast() }
	}
}

impl Default for GcFloatRegNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcFloatRegNode {}

pub const NONE_GC_FLOAT_REG_NODE: Option<&GcFloatRegNode> = None;

impl fmt::Display for GcFloatRegNode {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str("GcFloatRegNode")
	}
}
