// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::DomElement;
use crate::DomNode;
use crate::GcConverter;
use crate::GcFeatureNode;
use crate::GcInteger;
use crate::GcNode;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
	#[doc(alias = "ArvGcIntConverterNode")]
	pub struct GcIntConverterNode(Object<ffi::ArvGcIntConverterNode, ffi::ArvGcIntConverterNodeClass>) @extends GcConverter, GcFeatureNode, GcNode, DomElement, DomNode, @implements GcInteger;

	match fn {
		type_ => || ffi::arv_gc_int_converter_node_get_type(),
	}
}

impl GcIntConverterNode {
	#[doc(alias = "arv_gc_int_converter_node_new")]
	pub fn new() -> GcIntConverterNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_int_converter_node_new()).unsafe_cast() }
	}
}

impl Default for GcIntConverterNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcIntConverterNode {}

impl fmt::Display for GcIntConverterNode {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str("GcIntConverterNode")
	}
}
