// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use DomElement;
use DomNode;
use GcNode;
use GcPropertyNode;
use aravis_sys;
use glib;
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::ptr;

glib_wrapper! {
    pub struct GcIndexNode(Object<aravis_sys::ArvGcIndexNode, aravis_sys::ArvGcIndexNodeClass, GcIndexNodeClass>) @extends GcPropertyNode, GcNode, DomElement, DomNode;

    match fn {
        get_type => || aravis_sys::arv_gc_index_node_get_type(),
    }
}

impl GcIndexNode {
    pub fn new() -> GcIndexNode {
        assert_initialized_main_thread!();
        unsafe {
            GcNode::from_glib_full(aravis_sys::arv_gc_index_node_new()).unsafe_cast()
        }
    }
}

impl Default for GcIndexNode {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_GC_INDEX_NODE: Option<&GcIndexNode> = None;

pub trait GcIndexNodeExt: 'static {
    fn get_index(&self, default_offset: i64) -> Result<i64, glib::Error>;
}

impl<O: IsA<GcIndexNode>> GcIndexNodeExt for O {
    fn get_index(&self, default_offset: i64) -> Result<i64, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = aravis_sys::arv_gc_index_node_get_index(self.as_ref().to_glib_none().0, default_offset, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }
}

impl fmt::Display for GcIndexNode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GcIndexNode")
    }
}
