// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, DomElement, DomNode, GcConverter, GcFeatureNode, GcInteger, GcNode};
use glib::{prelude::*, translate::*};

glib::wrapper! {
///
///
/// # Implements
///
/// [`GcConverterExt`][trait@crate::prelude::GcConverterExt], [`GcFeatureNodeExt`][trait@crate::prelude::GcFeatureNodeExt], [`GcNodeExt`][trait@crate::prelude::GcNodeExt], [`DomElementExt`][trait@crate::prelude::DomElementExt], [`DomNodeExt`][trait@crate::prelude::DomNodeExt], [`trait@glib::ObjectExt`], [`GcIntegerExt`][trait@crate::prelude::GcIntegerExt]
	#[doc(alias = "ArvGcIntConverterNode")]
	pub struct GcIntConverterNode(Object<ffi::ArvGcIntConverterNode, ffi::ArvGcIntConverterNodeClass>) @extends GcConverter, GcFeatureNode, GcNode, DomElement, DomNode, @implements GcInteger;

	match fn {
		type_ => || ffi::arv_gc_int_converter_node_get_type(),
	}
}

impl GcIntConverterNode {
	#[doc(alias = "arv_gc_int_converter_node_new")]
	pub fn new() -> GcIntConverterNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_int_converter_node_new()).unsafe_cast() }
	}
}

impl Default for GcIntConverterNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcIntConverterNode {}
