// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::DomElement;
use crate::DomNode;
use crate::GcFeatureNode;
use crate::GcNode;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
	#[doc(alias = "ArvGcPort")]
	pub struct GcPort(Object<ffi::ArvGcPort, ffi::ArvGcPortClass>) @extends GcFeatureNode, GcNode, DomElement, DomNode;

	match fn {
		type_ => || ffi::arv_gc_port_get_type(),
	}
}

impl GcPort {
	#[doc(alias = "arv_gc_port_new")]
	pub fn new() -> GcPort {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_port_new()).unsafe_cast() }
	}

	//#[doc(alias = "arv_gc_port_read")]
	//pub fn read(&self, buffer: /*Unimplemented*/Option<Fundamental: Pointer>, address: u64, length: u64) -> Result<(), glib::Error> {
	//    unsafe { TODO: call ffi:arv_gc_port_read() }
	//}

	//#[doc(alias = "arv_gc_port_write")]
	//pub fn write(&self, buffer: /*Unimplemented*/Option<Fundamental: Pointer>, address: u64, length: u64) -> Result<(), glib::Error> {
	//    unsafe { TODO: call ffi:arv_gc_port_write() }
	//}
}

impl Default for GcPort {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcPort {}

impl fmt::Display for GcPort {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str("GcPort")
	}
}
