// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::DomElement;
use crate::DomNode;
use crate::GcFeatureNode;
use crate::GcNode;
use crate::GcRegister;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
	#[doc(alias = "ArvGcRegisterNode")]
	pub struct GcRegisterNode(Object<ffi::ArvGcRegisterNode, ffi::ArvGcRegisterNodeClass>) @extends GcFeatureNode, GcNode, DomElement, DomNode, @implements GcRegister;

	match fn {
		type_ => || ffi::arv_gc_register_node_get_type(),
	}
}

impl GcRegisterNode {
	#[doc(alias = "arv_gc_register_node_new")]
	pub fn new() -> GcRegisterNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_register_node_new()).unsafe_cast() }
	}
}

impl Default for GcRegisterNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcRegisterNode {}

pub const NONE_GC_REGISTER_NODE: Option<&GcRegisterNode> = None;

impl fmt::Display for GcRegisterNode {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str("GcRegisterNode")
	}
}
