// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, DomElement, DomNode, GcFeatureNode, GcNode, GcString};
use glib::{prelude::*, translate::*};

glib::wrapper! {
///
///
/// # Implements
///
/// [`GcFeatureNodeExt`][trait@crate::prelude::GcFeatureNodeExt], [`GcNodeExt`][trait@crate::prelude::GcNodeExt], [`DomElementExt`][trait@crate::prelude::DomElementExt], [`DomNodeExt`][trait@crate::prelude::DomNodeExt], [`trait@glib::ObjectExt`], [`GcStringExt`][trait@crate::prelude::GcStringExt]
	#[doc(alias = "ArvGcStringNode")]
	pub struct GcStringNode(Object<ffi::ArvGcStringNode, ffi::ArvGcStringNodeClass>) @extends GcFeatureNode, GcNode, DomElement, DomNode, @implements GcString;

	match fn {
		type_ => || ffi::arv_gc_string_node_get_type(),
	}
}

impl GcStringNode {
	#[doc(alias = "arv_gc_string_node_new")]
	pub fn new() -> GcStringNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_string_node_new()).unsafe_cast() }
	}
}

impl Default for GcStringNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcStringNode {}
