// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::DomElement;
use crate::DomNode;
use crate::GcFeatureNode;
use crate::GcNode;
use crate::GcRegister;
use crate::GcRegisterNode;
use crate::GcString;
use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
	#[doc(alias = "ArvGcStringRegNode")]
	pub struct GcStringRegNode(Object<ffi::ArvGcStringRegNode, ffi::ArvGcStringRegNodeClass>) @extends GcRegisterNode, GcFeatureNode, GcNode, DomElement, DomNode, @implements GcRegister, GcString;

	match fn {
		type_ => || ffi::arv_gc_string_reg_node_get_type(),
	}
}

impl GcStringRegNode {
	///
	/// # Returns
	///
	/// a new StringReg node
	#[doc(alias = "arv_gc_string_reg_node_new")]
	pub fn new() -> GcStringRegNode {
		assert_initialized_main_thread!();
		unsafe { GcNode::from_glib_full(ffi::arv_gc_string_reg_node_new()).unsafe_cast() }
	}
}

impl Default for GcStringRegNode {
	fn default() -> Self {
		Self::new()
	}
}

unsafe impl Send for GcStringRegNode {}

pub const NONE_GC_STRING_REG_NODE: Option<&GcStringRegNode> = None;

impl fmt::Display for GcStringRegNode {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str("GcStringRegNode")
	}
}
